presets:
  - name: genre_normalized_none
    params:
      analyze_type: 'analyze_genres'
      metrics: ['calinski_harabasz', 'davies_bouldin', 'silhouette_score', 'inter_intra', 'soft_fuzzy_dunn', 'soft_fuzzy_silhouette', 'xie_beni_index']
      normalize_map: [true, true, true, true, true]
      pca_dim: 0
      dim_red: ['pca', 'umap'] #, 'tsne', 'phate', 'pacmap']
  - name: genre_normalized_50
    params:
      analyze_type: 'analyze_genres'
      metrics: ['soft_fuzzy_dunn', 'soft_fuzzy_silhouette', 'xie_beni_index']
      normalize_map: [true, true, true, true, true]
      pca_dim: 50
      dim_red: ['pca'] #, 'umap'] #, 'tsne', 'phate', 'pacmap']
  - name: genre_normalized_100
    params:
      analyze_type: 'analyze_genres'
      metrics: ['soft_fuzzy_dunn', 'soft_fuzzy_silhouette', 'xie_beni_index']
      normalize_map: [true, true, true, true, true]
      pca_dim: 50
      dim_red: ['pca', 'umap'] #, 'tsne', 'phate', 'pacmap']
  - name: genre_no_normalized_none
    params:
      analyze_type: 'analyze_genres'
      metrics: ['calinski_harabasz', 'davies_bouldin', 'silhouette_score', 'inter_intra', 'soft_fuzzy_dunn', 'soft_fuzzy_silhouette', 'xie_beni_index']
      normalize_map: [false, false, false, false, false]
      pca_dim: 0
      dim_red: ['pca', 'umap'] #, 'tsne', 'phate', 'pacmap']
  - name: genre_no_normalized_50
    params:
      analyze_type: 'analyze_genres'
      metrics: ['calinski_harabasz', 'davies_bouldin', 'silhouette_score', 'inter_intra', 'soft_fuzzy_dunn', 'soft_fuzzy_silhouette', 'xie_beni_index']
      normalize_map: [false, false, false, false, false]
      pca_dim: 50
      dim_red: ['pca', 'umap'] #, 'tsne', 'phate', 'pacmap']
  - name: genre_no_normalized_100
    params:
      analyze_type: 'analyze_genres'
      metrics: ['calinski_harabasz', 'davies_bouldin', 'silhouette_score', 'inter_intra', 'soft_fuzzy_dunn', 'soft_fuzzy_silhouette', 'xie_beni_index']
      normalize_map: [false, false, false, false, false]
      pca_dim: 100 
      dim_red: ['pca', 'umap'] #, 'tsne', 'phate', 'pacmap']
