presets:
  - name: title_normalized_none
    params:
      analyze_type: 'analyze_titles'
      metrics: ['calinski_harabasz', 'davies_bouldin', 'silhouette_score', 'inter_intra']
      normalize_map: [true, true, true, true, true]
      pca_dim: 0
      dim_red: ['pca', 'umap'] #, 'tsne', 'phate', 'pacmap']
  - name: title_normalized_50
    params:
      analyze_type: 'analyze_titles'
      metrics: ['calinski_harabasz', 'davies_bouldin', 'silhouette_score'] #, 'inter_intra']
      normalize_map: [true, true, true, true, true]
      pca_dim: 50
      dim_red: ['pca'] #, 'umap'] #, 'tsne', 'phate', 'pacmap']
  - name: title_normalized_100
    params:
      analyze_type: 'analyze_titles'
      metrics: ['calinski_harabasz', 'davies_bouldin', 'silhouette_score'] #, 'inter_intra']
      normalize_map: [true, true, true, true, true]
      pca_dim: 50
      dim_red: ['pca', 'umap'] #, 'tsne', 'phate', 'pacmap']
  - name: title_no_normalized_none
    params:
      analyze_type: 'analyze_titles'
      metrics: ['calinski_harabasz', 'davies_bouldin', 'silhouette_score', 'inter_intra']
      normalize_map: [false, false, false, false, false]
      pca_dim: 0
      dim_red: ['pca', 'umap'] #, 'tsne', 'phate', 'pacmap']
  - name: title_no_normalized_50
    params:
      analyze_type: 'analyze_titles'
      metrics: ['calinski_harabasz', 'davies_bouldin', 'silhouette_score', 'inter_intra']
      normalize_map: [false, false, false, false, false]
      pca_dim: 50
      dim_red: ['pca', 'umap'] #, 'tsne', 'phate', 'pacmap']
  - name: title_no_normalized_100
    params:
      analyze_type: 'analyze_titles'
      metrics: ['calinski_harabasz', 'davies_bouldin', 'silhouette_score', 'inter_intra']
      normalize_map: [false, false, false, false, false]
      pca_dim: 100 
      dim_red: ['pca', 'umap'] #, 'tsne', 'phate', 'pacmap']


