stages:
  download:
    cmd: python -m download_datasets.download_datasets_all --datasets ${datasets}
    deps:
      - download_datasets/download_datasets_all.py
      - params.yaml
    outs:
      - downloads/
    params:
      - datasets

  preprocess_datasets:
    cmd: python -m preprocess_datasets.preprocess_datasets_all --datasets ${datasets}
    deps:
      - downloads/
      - preprocess_datasets/preprocess_datasets_all.py
    outs:
      - datasets/
    params:
      - datasets
