stages:
  download:
    cmd: python -m src.download_datasets.download_datasets_all
    deps:
      - src/download_datasets/download_datasets_all.py
      - params.yaml
    outs:
      - data/downloads/:
          persist: true
    params:
      - datasets_download

  preprocess_datasets:
    cmd: python -m src.preprocess_datasets.preprocess_datasets_all
    deps:
      - data/downloads/
      - src/preprocess_datasets/preprocess_datasets_all.py
      - params.yaml
    outs:
      - data/datasets/:
          persist: true
    params:
      - preprocess_datasets

  chunking_text:
    cmd:
      python -m src.chunking.chunking_text_all
    deps:
      - data/datasets/
      - src/chunking/chunking_text_all.py
      - params.yaml
    outs:
      - data/chunks/:
          persist: true
    params:
      - preprocess_datasets.datasets
      - chunking.methods

  embed_chunks:
    cmd: python -m src.embed_chunks.embed_chunks_all
    deps:
      - data/chunks/
      - src/embed_chunks/embed_chunks_all.py
      - params.yaml
    outs:
      - data/vector_db/:
          persist: true
    params:
      - preprocess_datasets.datasets
      - chunking.methods
      - vector_embed.methods

  search:
    cmd: python -m src.search.search_all
    deps:
      - data/vector_db/
      - src/search/search_all.py
      - params.yaml
    outs:
      - data/search_result/:
          persist: true
    params:
      - preprocess_datasets.datasets
      - chunking.methods
      - vector_embed.methods
      - search.methods

  rerank:
    cmd: python -m src.rerank.rerank_all
    deps:
      - data/search_result/
      - src/rerank/rerank_all.py
      - params.yaml
    outs:
      - data/rerank_result/:
          persist: true
    params:
      - preprocess_datasets.datasets
      - chunking.methods
      - vector_embed.methods
      - search.methods
      - rerank.methods

  generation:
    cmd: python -m src.generation.generation_all
    deps:
      - data/rerank_result/
      - src/generation/generation_all.py
      - params.yaml
    outs:
      - data/generation_result/:
          persist: true
    params:
      - preprocess_datasets.datasets
      - chunking.methods
      - vector_embed.methods
      - search.methods
      - rerank.methods
      - generation.methods

  evaluate_generator:
    cmd: python -m src.evaluate_generator.evaluate_generator_all
    deps:
      - data/generation_result/
      - src/evaluate_generator/evaluate_generator_all.py
      - params.yaml
    outs:
      - data/evaluate_generator_result/:
          persist: true
    params:
      - preprocess_datasets.datasets
      - chunking.methods
      - vector_embed.methods
      - search.methods
      - rerank.methods
      - generation.methods
      - evaluate_generator.methods

  analyze_split_point:
    cmd: python -m src.analyze_split_point.analyze_split_point_all
    deps:
      - data/chunks/
      - src/analyze_split_point/analyze_split_point_all.py
      - params.yaml
    outs:
      - data/analyze_split_points/:
          persist: true
    params:
      - preprocess_datasets.datasets
      - chunking.methods
      - analyze_split_points.methods

  analyze_retrieval:
    cmd: python -m src.analyze_retrieval.analyze_retrieval_all
    deps:
      - data/rerank_result/
      - src/analyze_retrieval/analyze_retrieval_all.py
      - params.yaml
    outs:
      - data/analyze_retrieval/:
          persist: true
    params:
      - preprocess_datasets.datasets
      - chunking.methods
      - vector_embed.methods
      - search.methods
      - rerank.methods
      - analyze_retrieval.methods

