datasets_download:
  - "infiniteBench"
  # - "novelQA"
  # - "literaryQA"

preprocess_datasets:
  tokenizer:
    backend: tiktoken
    model_name: gpt-4
  datasets:
    # literaryQA:
    #   presets_file: configs/preprocess_dataset/literaryQA.yaml
    #   use_presets:
    #     - default  # 'chapter' or 'page' or 'none'
    # novelQA:
    #   presets_file: configs/preprocess_dataset/novelQA.yaml
    #   use_presets:
    #     - default  # 'chapter' or 'page' or 'none'
    # infiniteBenchQA:
    #   presets_file: configs/preprocess_dataset/infiniteBenchQA.yaml
    #   use_presets:
    #     - default  # 'chapter' or 'page' or 'none'
    infiniteBenchChoice:
      presets_file: configs/preprocess_dataset/infiniteBenchChoice.yaml
      use_presets:
        - default  # 'chapter' or 'page' or 'none'

chunking:
  splits: ["example"]
  methods:
    fixed_size:
      presets_file: configs/chunking/fixed_size.yaml
      use_presets:
        - fs_512_64_char
        - fs_512_64_token
    recursive:
      presets_file: configs/chunking/recursive.yaml
      use_presets:
        - r_512_64
    # recursive_semantic:
    #   presets_file: configs/chunking/recursive_semantic.yaml
    #   use_presets:
    #     - paper_based
    neural:
      presets_file: configs/chunking/neural.yaml
      use_presets:
        - default
    chonkie_semantic:
      presets_file: configs/chunking/chonkie_semantic.yaml
      use_presets:
        - default
    lumber:
      presets_file: configs/chunking/lumber.yaml
      use_presets:
        - default
    max_min:
      presets_file: configs/chunking/max_min.yaml
      use_presets:
        - liberal
    sequential_hac:
      presets_file: configs/chunking/sequential_hac.yaml
      use_presets:
        - liberal

vector_embed:
  methods:
    FAISS:
      presets_file: configs/vector_embed/faiss.yaml
      use_presets:
        - default_global
        # - default_local

search:
  methods:
    faiss:
      presets_file: configs/search/faiss.yaml
      use_presets:
        - default_top10

rerank:
  methods:
    # nothing:
    #   presets_file: configs/rerank/nothing.yaml
    #   use_presets:
    #     - default_top3
    #     - default_top3_op
    reranker:
      presets_file: configs/rerank/reranker.yaml
      use_presets:
        - default_top5
        # - default_top3_op

generation:
  methods:
    generate_fixed_token:
      presets_file: configs/generation/generate_fixed_token.yaml
      use_presets:
        - qwen_4b

evaluate_generator:
  methods:
    llm_as_a_judge:
      presets_file: configs/evaluate_generator/llm_as_a_judge.yaml
      use_presets:
        - qwen_4b
