[project]
name = "my-project"
version = "0.1.0"
description = "Example project"
requires-python = "==3.12.3"
dependencies = [
    "vllm==0.19.1",
    "datasets",
    "ipywidgets==8.1.5",
    "huggingface-hub",
    "python-dotenv",
    "dvc",
    "mlflow",
    "langchain-text-splitters",
    "tiktoken",
    "transformers",
    "pyyaml",
    "black",
    "isort",
    "flake8",
    "pyproject-flake8==7.0.0",
    "Flake8-pyproject",
    "faiss-cpu",
    "tqdm",
    "numpy",
    "langchain-experimental>=0.4.1",
    "langchain>=0.2.0",
    "langchain-experimental>=0.4.1",
    "langchain-text-splitters>=1.1.1",
    "langchain-huggingface>=1.2.0",
    "sentence-transformers>=5.1.2",
    "nltk>=3.8.1",
    "torch>=2.10.0",
    "chonkie",
    "chonkie[model2vec]",
    "accelerate",
    "openai",
    "transformers==4.57.6",
    "FlagEmbedding==1.4.0",
    "bs4>=0.0.2",
    "chardet>=5.2.0",
    "datasets>=4.1.1",
    "ftfy>=6.3.1",
    "html5lib>=1.1",
    "loguru>=0.7.3",
    "rouge-score>=0.1.2",
    "typed-argument-parser>=1.11.0",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
  { index = "pytorch-cu128", marker = "sys_platform == 'linux'" }
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.venv
  | tmp_venv
  | .*\.tmp_venv.*
  | build
  | dist
  | __pycache__
  | downloads
  | \.dvc
  | \.dvc/cache
)/
'''

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["src"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = [".venv", "build", "dist", "__pycache__", "downloads", ".dvc", ".dvc/cache",".tmp_venv"]

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203", "W503"]
exclude = [
    "venv",
    ".venv",
    "build",
    "dist",
    "__pycache__",
    "downloads",
    ".dvc",
    ".dvc/cache",
    ".tmp_venv",
]