presets:
  - name: default_global
    params:
      embbeder: /home/mahuk/chunking-thesis/models/BAAI/bge-m3
      batch_size: 32
      dtype: float32
      embed_type: global
  - name: default_local
    params:
      embbeder: /home/mahuk/chunking-thesis/models/BAAI/bge-m3
      batch_size: 32
      dtype: float32
      embed_type: local

