presets:
  - name: default_top5
    params:
      embbeder: all-MiniLM-L6-v2
      top_k: 5
  - name: default_top10
    params:
      embbeder: all-MiniLM-L6-v2
      top_k: 10
  - name: default_top20
    params:
      embbeder: all-MiniLM-L6-v2
      top_k: 20

