presets:
  - name: default_top3
    params:
      top_k: 3
      order_preverse: false
  - name: default_top3_op
    params:
      top_k: 3
      order_preverse: true
  - name: default_top5
    params:
      top_k: 5
      order_preverse: false
  - name: default_top5_op
    params:
      top_k: 5
      order_preverse: true
  - name: default_top10_op
    params:
      top_k: 10
      order_preverse: true
  - name: default_top10
    params:
      top_k: 10
      order_preverse: false


