presets:
  - name: default
    params:
      embedding_model: /home/mahuk/chunking-thesis/models/minishlab/potion-base-32M
      chunk_size: 2048
      similarity_window: 3
      skip_window: 0
      threshold: 0.8
      filter_window: 5
      filter_polyorder: 3
      filter_tolerance: 0.02

  - name: skip_window
    params:
      embedding_model: /home/mahuk/chunking-thesis/models/minishlab/potion-base-32M
      chunk_size: 2048
      similarity_window: 3
      skip_window: 1
      threshold: 0.8
      filter_window: 5
      filter_polyorder: 3
      filter_tolerance: 0.02
  
  - name: norm
    params:
      embedding_model: /home/mahuk/chunking-thesis/models/minishlab/potion-base-32M
      chunk_size: 2048
      similarity_window: 3
      skip_window: 0
      threshold: 0.85
      filter_window: 5
      filter_polyorder: 3
      filter_tolerance: 0.036