presets:
  - name: default
    params:
      model_name: BAAI/bge-m3
      hard_threshold: 0.6
      c_param: 0.9
      init_const: 1.5
  - name: liberal
    params:
      model_name: BAAI/bge-m3
      hard_threshold: 0.52
      c_param: 0.6
      init_const: 2
  - name: norm
    params:
      model_name: BAAI/bge-m3
      hard_threshold: 0.479
      c_param: 0.92 # 0.9
      init_const: 1.4 # 1.5