presets:
  - name: r_512_64
    params:
      chunk_size: 512
      min_characters_per_chunk: 32
  - name: r_1024_128
    params:
      chunk_size: 1024
      min_characters_per_chunk: 64
  - name: r_2048_256
    params:
      chunk_size: 2048
      min_characters_per_chunk: 128
  - name: norm
    params:
      chunk_size: 1550
      min_characters_per_chunk: 96