presets:
  - name: qwen_4b
    params:
      inference_mode: hf
      model: /home/mahuk/chunking-thesis/models/Qwen/Qwen3-4B-Instruct-2507
      token_limit: 8192
      max_new_tokens: 512
      prompt_template: default_prompt
      tokenizer_backend: hf
      tokenizer_model_name: /home/mahuk/chunking-thesis/models/Qwen/Qwen3-4B-Instruct-2507
  - name: gpt_20b_4096
    params:
      inference_mode: api
      model: openai/gpt-oss-20b
      token_limit: 4788 # 4096 max + 512 new tokens + 150 sys prompt + 30 question
      max_new_tokens: 4788
      prompt_template: default_prompt
      tokenizer_backend: hf
      tokenizer_model_name: /workspace/chunking_thesis/models/openai/gpt-oss-20b
  - name: gpt_20b_2048
    params:
      inference_mode: api
      model: openai/gpt-oss-20b
      token_limit: 2740 # 2048 max + 512 new tokens + 150 sys prompt + 30 question
      max_new_tokens: 4788
      prompt_template: default_prompt
      tokenizer_backend: hf
      tokenizer_model_name: /workspace/chunking_thesis/models/openai/gpt-oss-20b

