presets:
  - name: qwen_4b
    params:
      inference_mode: hf
      model: Qwen/Qwen3-4B-Instruct-2507
      token_limit: 8192
      max_new_tokens: 512
      prompt_template: default_prompt
      tokenizer_backend: Qwen/Qwen3-4B-Instruct-2507
      tokenizer_model_name: hf
  - name: deepseek_1_5b
    params:
      inference_mode: hf  
      model: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
      token_limit: 8192
      max_new_tokens: 512
      prompt_template: default_prompt
      tokenizer_backend: Qwen/Qwen3-4B-Instruct-2507
      tokenizer_model_name: hf

